### PR TITLE
Modify RxSwift dependency version range

### PR DESCRIPTION
**Pull request by nnsnodnb**
I modified updatable to RxSwift 6.x.x .

Best Regard,

### CODE REVIEW

**Comment by kean** [comment]
Thanks!

**Comment by nnsnodnb** [comment]
Thank you for your support.

Can you also deliver to CocoaPods?

**Comment by kean** [comment]
RxNuke (2.0.1) successfully published
March 15th, 10:06

**Comment by nnsnodnb** [comment]
Thanks🎉

**Pull request merged**
