### PR TITLE
migrate to swift 5

### PR DESCRIPTION
**Pull request by ostk0069**
I did migration for swift 5
I update the WATCHOS_DEVELOPMENT_TARGET to 3.0 from 2.0 because RxSwift said so.
```
RxNuke.swift:6:8: error: compiling for watchOS 2.0, but module 'RxSwift' has a minimum deployment target of watchOS 3.0
```

### CODE REVIEW

**Comment by ostk0069** [comment]
I found another updates that `WATCHOS_DEVELOPMENT_TARGET = 3.0` did not work well, and `4.0` would work successfully.

**Comment by kean** [comment]
This looks good, thanks @takumaosada! I'm merging as is, will update if needed and release a new version soon. I already released [Nuke 7.6 with Swift 5](https://github.com/kean/Nuke/releases/tag/7.6) a few hours ago.

**Comment by kean** [comment]
@takumaosada new version released https://github.com/kean/RxNuke/releases/tag/0.8

**Comment by ostk0069** [comment]
thanks for the review & update! 👍

**Pull request merged**
